#!/usr/bin/env bash
# Derived from https://github.com/docker-library/postgres/blob/master/update.sh
set -Eeuo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

matrixVersions=( */Dockerfile )
matrixVersions=( "${matrixVersions[@]%/Dockerfile}" )

versions=( "$@" )
fullMatrixUpdate=false
if [ ${#versions[@]} -eq 0 ]; then
    fullMatrixUpdate=true
    versions=( "${matrixVersions[@]}" )
fi
versions=( "${versions[@]%/Dockerfile}" )

dockerlistsDir=.
if [ "$fullMatrixUpdate" = false ]; then
    dockerlistsDir="$(mktemp -d)"
    trap 'rm -rf "$dockerlistsDir"' EXIT
fi

for optimized in debian alpine test; do
    rm -f "$dockerlistsDir/_dockerlists_${optimized}.md"
    echo "<!-- This part is automatically generated by ./update.sh. Do not modify this section manually. -->" > "$dockerlistsDir/_dockerlists_${optimized}.md"
    echo "| DockerHub image | Dockerfile | OS | Postgres | PostGIS |" >> "$dockerlistsDir/_dockerlists_${optimized}.md"
    echo "| --------------- | ---------- | -- | -------- | ------- |" >> "$dockerlistsDir/_dockerlists_${optimized}.md"
done

autogenerated='NOTE: THIS DOCKERFILE IS GENERATED VIA "make update"! PLEASE DO NOT EDIT IT DIRECTLY.'

dockerhublink="https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name="
githubrepolink="https://github.com/postgis/docker-postgis/blob/master"

# Process version directories in ascending order for stable generated output.
mapfile -t versions < <(printf '%s\n' "${versions[@]}" | sort -V)

defaultAlpineSuite='3.24'
declare -A debianSuite=(
    [14]='bookworm'
    [15]='bookworm'
    [16]='bookworm'
    [17]='bookworm'
    [18]='bookworm'
    [19]='bookworm'
)

declare -A postgisDebPkgNameVersionSuffixes=(
    [3.5]='3'
    [3.6]='3'
    [3.7]='3'
)

packagesBase='https://apt.postgresql.org/pub/repos/apt/dists/'

curl_retry_args=(
    --fail
    --silent
    --show-error
    --location
    --retry 5
    --retry-delay 2
    --retry-connrefused
)
curl_download() {
    curl "${curl_retry_args[@]}" "$@"
}

sed_in_place() {
    if sed --version >/dev/null 2>&1; then
        sed -i "$@"
    else
        sed -i '' "$@"
    fi
}

git_ls_remote() {
    git -c http.maxRetries=5 -c http.retryDelay=2 ls-remote "$@"
}

warning() {
    echo "WARNING: $*" >&2
}

officialPostgresLibraryUrl='https://raw.githubusercontent.com/docker-library/official-images/master/library/postgres'
if ! officialPostgresLibrary="$(curl_download "$officialPostgresLibraryUrl")"; then
    warning "cannot fetch the official PostgreSQL image metadata; Alpine suite discovery is unavailable"
    exit 1
fi

declare -A knownPostgresTags=()
knownPostgisSeries=()
knownStablePostgisSeries=()
warnedPostgisSeries=()
maxKnownPostgresMajor=0
maxKnownPostgisMinor=0

for version in "${matrixVersions[@]}"; do
    IFS=- read -r postgresTag postgisTag <<< "$version"
    knownPostgresTags["$postgresTag"]=1

    postgresMajor="$(printf '%s\n' "$postgresTag" | sed -E 's/[^0-9].*//')"
    if [ -n "$postgresMajor" ] && (( postgresMajor > maxKnownPostgresMajor )); then
        maxKnownPostgresMajor=$postgresMajor
    fi

    if [[ "$postgisTag" =~ ^3\.[0-9]+$ ]]; then
        postgisSeries="$postgisTag"
        postgisMinor="${postgisSeries#3.}"
        knownPostgisSeries+=("$postgisSeries")
        for dockerfile in "$version/Dockerfile" "$version/alpine/Dockerfile"; do
            if [ -f "$dockerfile" ] && grep -Eq '^ENV POSTGIS_VERSION=[^[:space:]]+$' "$dockerfile" && ! grep -Eq '^ENV POSTGIS_VERSION=.*(alpha|beta|rc)' "$dockerfile"; then
                knownStablePostgisSeries+=("$postgisSeries")
                break
            fi
        done
        if (( postgisMinor > maxKnownPostgisMinor )); then
            maxKnownPostgisMinor=$postgisMinor
        fi
    fi
done

officialPostgresReleaseTags="$(printf '%s\n' "$officialPostgresLibrary" | awk '
    /^Tags:/ {
        sub(/^Tags:[[:space:]]*/, "")
        count = split($0, tags, /,[[:space:]]*/)
        for (i = 1; i <= count; i++) {
            if (tags[i] ~ /^[0-9]+(alpha[0-9]+|beta[0-9]+|rc[0-9]+)?$/) {
                print tags[i]
            }
        }
    }
' | sort -Vu)"

for upstreamPostgresTag in $officialPostgresReleaseTags; do
    if [ -n "${knownPostgresTags["$upstreamPostgresTag"]:+set}" ]; then
        continue
    fi

    upstreamPostgresMajor="$(printf '%s\n' "$upstreamPostgresTag" | sed -E 's/[^0-9].*//')"
    if (( upstreamPostgresMajor >= maxKnownPostgresMajor )); then
        warning "PostgreSQL image tag ${upstreamPostgresTag} is not represented in the matrix; update.sh will not create or rename a directory"
    fi
done

cgalGitBranch='6.2.x-branch'
cgalGitHash="$(git_ls_remote https://github.com/CGAL/cgal.git "heads/${cgalGitBranch}" | awk '{ print $1}')"
sfcgalGitHash="$(git_ls_remote https://gitlab.com/SFCGAL/SFCGAL.git heads/master | awk '{ print $1}')"
projGitHash="$(git_ls_remote https://github.com/OSGeo/PROJ.git heads/master | awk '{ print $1}')"
gdalGitHash="$(git_ls_remote https://github.com/OSGeo/gdal.git refs/heads/master | awk '$2 == "refs/heads/master" { print $1 }')"
geosGitHash="$(git_ls_remote https://github.com/libgeos/geos.git heads/main | awk '{ print $1}')"
postgisGitHash="$(git_ls_remote https://github.com/postgis/postgis.git heads/master | awk '{ print $1}')"
h3PgGitHash="$(git_ls_remote https://github.com/postgis/h3-pg.git heads/main | awk '{ print $1}')"
addressStandardizerGitHash="$(git_ls_remote https://github.com/postgis/address_standardizer.git heads/main | awk '{ print $1}')"
addressStandardizerReleaseGitHash="$(git_ls_remote --tags --refs https://github.com/postgis/address_standardizer.git refs/tags/v3.7.0 | awk '$2 == "refs/tags/v3.7.0" { print $1 }')"
if [ -z "$addressStandardizerReleaseGitHash" ]; then
    warning "cannot discover the address_standardizer v3.7.0 release tag"
    exit 1
fi
nlohmannJsonVersion="$(git_ls_remote --tags --refs https://github.com/nlohmann/json.git 'refs/tags/v*' | sed -n 's#.*refs/tags/v\([0-9][0-9.]*\)$#\1#p' | sort -V | tail -n 1 || true)"
if [ -z "$nlohmannJsonVersion" ]; then
    warning "cannot discover a stable nlohmann/json release"
    exit 1
fi
pgroutingLatestVersion="$(git_ls_remote --tags --refs https://github.com/pgRouting/pgrouting.git 'refs/tags/v*' | sed -n 's#.*refs/tags/v\([0-9][0-9.]*\)$#\1#p' | sort -V | tail -n 1 || true)"
if [ -z "$pgroutingLatestVersion" ]; then
    warning "cannot discover a stable pgRouting release"
    exit 1
fi
tigerGeocoderArchive="$(curl_download 'https://download.osgeo.org/postgis/source/postgis_tiger_geocoder/' | grep -oE 'postgis_tiger_geocoder-[0-9]+\.[0-9]+\.tar\.gz' | sort -Vu | tail -n 1 || true)"
if [ -z "$tigerGeocoderArchive" ]; then
    warning "cannot discover a standalone Tiger Geocoder release from OSGeo"
    exit 1
fi
tigerGeocoderVersion="${tigerGeocoderArchive#postgis_tiger_geocoder-}"
tigerGeocoderVersion="${tigerGeocoderVersion%.tar.gz}"
tigerGeocoderSha256="$(curl_download "https://download.osgeo.org/postgis/source/postgis_tiger_geocoder/${tigerGeocoderArchive}" | sha256sum | awk '{ print $1 }')"

#-------------------------------------------
# Correct version sorting
function version_reverse_sort() {
    # This function sorts version numbers in reverse order,
    # ensuring that versions without pre-release tags (e.g., "3.4.0")
    # are ranked higher than those with pre-release tags (e.g., "3.4.0rc4").
    # It adds a ".9991" suffix to versions without pre-release tags,
    # sorts them with `sort -Vr`, and then removes the ".9991" suffix.
    sed -r "s/([0-9]+\.[0-9]+\.[0-9]+$)/\1\.9991/" | sort -Vr | sed s/\.9991$//
}

api_preference="github"
function fetch_postgis_versions() {
    # get all postgis versions from github
    local REPO="postgis/postgis"
    local PER_PAGE=100 # You can ask for up to 100 results per page
    local page=1
    postgis_all_v3_versions=""

    while true; do
        local response
        if [ "$api_preference" == "github" ]; then
            response=$(curl_download "https://api.github.com/repos/$REPO/tags?per_page=$PER_PAGE&page=$page") || {
                echo "Failed to fetch postgis_versions from api.github.com/repos/$REPO/tags"
                return 1
            }
        elif [ "$api_preference" == "osgeo" ]; then
            response=$(curl_download "https://git.osgeo.org/gitea/api/v1/repos/${REPO}/tags?page=$page&limit=$PER_PAGE") || {
                echo "Failed to fetch postgis_versions from git.osgeo.org/gitea/api/v1/repos/${REPO}/tags"
                return 1
            }
        fi

        # Check for rate limit exceeded error - related to api.github.com
        if echo "$response" | grep -q "API rate limit exceeded"; then
            echo "Error: API rate limit exceeded!"
            echo "$response"
            exit 1
        fi

        # Extract tag names from the JSON response
        local tags
        tags=$(echo "$response" | sed -nE 's/.*"name":[[:space:]]*"([^"]+)".*/\1/p' || true)
        local count
        count=$(echo "$tags" | sed '/^$/d' | wc -l)

        if ((count == 0)); then
            break
        fi

        if ((page > 12)); then
            echo "Too many pages: ${page} - exiting; unexpected and something is wrong!"
            exit 1
        fi

        postgis_all_v3_versions+=" $tags"

        ((page++))
    done
}

fetch_postgis_versions || {
    echo "Error fetching postgis versions! Maybe network or server error!"
    exit 1
}

# Keep 3.* versions only
postgis_all_v3_versions=$(echo "$postgis_all_v3_versions" | sed '/^$/d' | grep '^3\.' | version_reverse_sort)
postgis_all_v3_versions_array_string=$(echo "$postgis_all_v3_versions" | tr '\n' ' ')
echo "postgis_all_v3_versions_array_string = ${postgis_all_v3_versions_array_string}"
echo " "

function select_postgis_source_version() {
    local series="$1"
    local selected

    selected="$(printf '%s\n' "$postgis_all_v3_versions" | grep -E "^${series}\\.[0-9]+$" | version_reverse_sort | head -n 1 || true)"
    if [ -z "$selected" ]; then
        selected="$(printf '%s\n' "$postgis_all_v3_versions" | grep -E "^${series}\\.[0-9]+(alpha[0-9]+|beta[0-9]+|rc[0-9]+)$" | version_reverse_sort | head -n 1 || true)"
    fi
    if [ -z "$selected" ]; then
        echo "ERROR: no PostGIS source release found for series ${series}" >&2
        return 1
    fi
    printf '%s\n' "$selected"
}

officialPostgisReleaseTags="$(printf '%s\n' "$postgis_all_v3_versions" | grep -E '^3\.[0-9]+\.[0-9]+(alpha[0-9]+|beta[0-9]+|rc[0-9]+)?$' | version_reverse_sort || true)"
for upstreamPostgisTag in $officialPostgisReleaseTags; do
    upstreamPostgisSeries="$(printf '%s\n' "$upstreamPostgisTag" | sed -E 's/^([0-9]+\.[0-9]+)\..*$/\1/')"
    upstreamPostgisMinor="${upstreamPostgisSeries#3.}"
    isStablePostgisRelease=true
    if [[ "$upstreamPostgisTag" =~ alpha|beta|rc ]]; then
        isStablePostgisRelease=false
    fi
    knownPostgisSeriesPresent=false
    if printf '%s\n' "${knownPostgisSeries[@]}" | grep -Fxq "$upstreamPostgisSeries"; then
        knownPostgisSeriesPresent=true
    fi
    if printf '%s\n' "${knownStablePostgisSeries[@]}" | grep -Fxq "$upstreamPostgisSeries"; then
        continue
    fi
    if [ "$isStablePostgisRelease" = false ] && [ "$knownPostgisSeriesPresent" = true ]; then
        continue
    fi
    if [ "$knownPostgisSeriesPresent" = false ] && (( upstreamPostgisMinor <= maxKnownPostgisMinor )); then
        continue
    fi
    if ! printf '%s\n' "${warnedPostgisSeries[@]}" | grep -Fxq "$upstreamPostgisSeries"; then
        if [ "$isStablePostgisRelease" = true ] && [ "$knownPostgisSeriesPresent" = true ]; then
            warning "PostGIS release ${upstreamPostgisTag} is stable but the matrix only contains a prerelease for series ${upstreamPostgisSeries}; update.sh will not rename a directory"
        else
            warning "PostGIS series ${upstreamPostgisSeries} (latest discovered tag ${upstreamPostgisTag}) is not represented in the matrix; update.sh will not create or rename a directory"
        fi
        warnedPostgisSeries+=("$upstreamPostgisSeries")
    fi
done

declare -A alpineSuiteByPostgresTag=()
function alpine_suite_for() {
    local postgresTag="$1"
    local suites

    if [ -n "${alpineSuiteByPostgresTag["$postgresTag"]:+set}" ]; then
        printf '%s\n' "${alpineSuiteByPostgresTag["$postgresTag"]}"
        return
    fi

    suites="$(printf '%s\n' "$officialPostgresLibrary" | awk -v wanted="$postgresTag" '
        function reset() {
            tagMatch = 0
            architectureMatch = 0
            directory = ""
        }
        function finish(   suite) {
            if (!tagMatch || !architectureMatch || directory == "") {
                reset()
                return
            }
            suite = directory
            sub(/^.*\//, "", suite)
            sub(/^alpine/, "", suite)
            if (suite ~ /^3\.[0-9]+$/) {
                print suite
            }
            reset()
        }
        BEGIN { reset() }
        /^Tags:/ {
            sub(/^Tags:[[:space:]]*/, "")
            count = split($0, tags, /,[[:space:]]*/)
            for (i = 1; i <= count; i++) {
                if (tags[i] == wanted "-alpine" || tags[i] ~ ("^" wanted "-alpine3\\.[0-9]+$")) {
                    tagMatch = 1
                }
            }
            next
        }
        /^Architectures:/ {
            if ($0 ~ /amd64([,[:space:]]|$)/ && $0 ~ /arm64v8([,[:space:]]|$)/) {
                architectureMatch = 1
            }
            next
        }
        /^Directory:/ {
            sub(/^Directory:[[:space:]]*/, "")
            directory = $0
            next
        }
        /^$/ { finish() }
        END { finish() }
    ' | sort -Vu)"

    if [ -z "$suites" ]; then
        warning "no official Alpine image for PostgreSQL ${postgresTag} with amd64 and arm64v8 metadata; retaining Alpine ${defaultAlpineSuite} as an unverified fallback"
        suites="$defaultAlpineSuite"
    else
        suites="$(printf '%s\n' "$suites" | tail -n 1)"
    fi

    alpineSuiteByPostgresTag["$postgresTag"]="$suites"
    printf '%s\n' "$suites"
}

#-------------------------------------------

declare -A suitePackageList=()
declare -A versionPackageList=()
function package_version() {
    local package="$1"
    awk -F ': ' -v package="$package" '$1 == "Package" { pkg = $2 } $1 == "Version" && pkg == package { print $2; exit }'
}

# Debian suites are tried in preference order, with the other supported suite
# available when PGDG has not published the requested package for that pair.
function debian_suite_candidates() {
    local postgresMajor="$1"
    local postgisVersion="${2:-}"
    local preferred="${debianSuite["$postgresMajor"]:-}"

    if [ -z "$preferred" ]; then
        return 1
    fi

    # Retain packaged PostGIS 3.5 images for PG14-17 while PGDG publishes them.
    if [ "$postgisVersion" = '3.5' ] && (( postgresMajor >= 14 && postgresMajor <= 17 )); then
        printf '%s\n' bullseye
    fi

    case "$preferred" in
        bookworm) printf '%s\n' bookworm trixie ;;
        trixie) printf '%s\n' trixie bookworm ;;
        *) return 1 ;;
    esac
}

function load_suite_package_metadata() {
    local suite="$1"
    local postgresMajor="$2"
    local arch packageKey packageList

    for arch in amd64 arm64; do
        packageKey="${suite}/${arch}"
        if [ -z "${suitePackageList["$packageKey"]+set}" ]; then
            if ! packageList="$(curl_download "${packagesBase}/${suite}-pgdg/main/binary-${arch}/Packages.bz2" | bunzip2)"; then
                return 1
            fi
            suitePackageList["$packageKey"]="$packageList"
        fi

        packageKey="${suite}/${postgresMajor}/${arch}"
        if [ -z "${versionPackageList["$packageKey"]+set}" ]; then
            if packageList="$(curl_download "${packagesBase}/${suite}-pgdg/${postgresMajor}/binary-${arch}/Packages.bz2" | bunzip2)"; then
                versionPackageList["$packageKey"]="$packageList"
            else
                versionPackageList["$packageKey"]=''
            fi
        fi
    done

    versionListAmd64="$(printf '%s\n%s\n' "${suitePackageList["${suite}/amd64"]}" "${versionPackageList["${suite}/${postgresMajor}/amd64"]}")"
    versionListArm64="$(printf '%s\n%s\n' "${suitePackageList["${suite}/arm64"]}" "${versionPackageList["${suite}/${postgresMajor}/arm64"]}")"
}

function select_debian_suite() {
    local postgresMajor="$1"
    local postgisVersion="$2"
    local candidateList candidateSuites suite postgresA postgresB postgisA postgisB
    local fallbackSuite='' mismatchMessage=''
    local postgisSeries='' postgisPackageSuffix='' postgisPackageName=''
    local -a candidates=()
    selectedSuite=''

    if [ "$postgisVersion" != master ]; then
        postgisSeries="$(printf '%s\n' "$postgisVersion" | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')"
        postgisPackageSuffix="${postgisDebPkgNameVersionSuffixes["$postgisSeries"]:-}"
        if [ -z "$postgisPackageSuffix" ]; then
            echo "ERROR: no Debian PGDG package mapping for PostGIS ${postgisSeries}" >&2
            return 1
        fi
        postgisPackageName="postgresql-${postgresMajor}-postgis-${postgisPackageSuffix}"
    fi

    if ! candidateList="$(debian_suite_candidates "$postgresMajor" "$postgisVersion")"; then
        echo "ERROR: no supported Debian suite mapping for PostgreSQL ${postgresMajor} / PostGIS ${postgisVersion}" >&2
        return 1
    fi
    mapfile -t candidates <<< "$candidateList"

    for suite in "${candidates[@]}"; do
        if ! load_suite_package_metadata "$suite" "$postgresMajor"; then
            continue
        fi
        postgresA="$(printf '%s\n' "$versionListAmd64" | package_version "postgresql-${postgresMajor}" || true)"
        postgresB="$(printf '%s\n' "$versionListArm64" | package_version "postgresql-${postgresMajor}" || true)"
        if [ "$postgresA" != "$postgresB" ]; then
            mismatchMessage="PostgreSQL ${postgresMajor} differs between amd64 (${postgresA:-missing}) and arm64 (${postgresB:-missing}) in Debian ${suite}"
            continue
        fi
        if [ -z "$postgresA" ]; then
            continue
        fi
        if [ "$postgisVersion" = master ]; then
            if [ -z "$fallbackSuite" ] && [ "$suite" != bullseye ]; then
                fallbackSuite="$suite"
            fi
            selectedSuite="$suite"
            break
        fi

        postgisA="$(printf '%s\n' "$versionListAmd64" | package_version "$postgisPackageName" || true)"
        postgisB="$(printf '%s\n' "$versionListArm64" | package_version "$postgisPackageName" || true)"
        if [ "$postgisA" != "$postgisB" ]; then
            mismatchMessage="${postgisPackageName} differs between amd64 (${postgisA:-missing}) and arm64 (${postgisB:-missing}) in Debian ${suite}"
            continue
        fi
        # Bullseye is package-only; source builds must use a supported suite.
        if [ -z "$fallbackSuite" ] && [ "$suite" != bullseye ]; then
            fallbackSuite="$suite"
        fi
        if [ -n "$postgisA" ]; then
            local packageSeries
            packageSeries="$(printf '%s\n' "$postgisA" | cut -d. -f1-2)"
            if [ "$packageSeries" = "$postgisSeries" ]; then
                selectedSuite="$suite"
                break
            fi
        fi
    done

    if [ -z "${selectedSuite:-}" ]; then
        if [ -z "$fallbackSuite" ]; then
            if [ -n "$mismatchMessage" ]; then
                echo "ERROR: ${mismatchMessage}" >&2
                return 1
            fi
            candidateSuites="$(printf '%s, ' "${candidates[@]}")"
            candidateSuites="${candidateSuites%, }"
            echo "ERROR: PostgreSQL ${postgresMajor} package is unavailable on both amd64 and arm64 in ${candidateSuites}" >&2
            return 1
        fi
        selectedSuite="$fallbackSuite"
    fi

    if ! load_suite_package_metadata "$selectedSuite" "$postgresMajor"; then
        echo "ERROR: unable to load PGDG metadata for Debian ${selectedSuite}" >&2
        return 1
    fi
}

function set_debian_dependencies() {
    local suite="$1"

    case "$suite" in
        bullseye)
            boostVersion="1.74.0"
            boostChronoVersion="1.74.0"
            sfcgalRuntimePackage="libsfcgal1"
            curlRuntimePackage="libcurl4"
            cfitsioRuntimePackage="libcfitsio9"
            fybaRuntimePackage="libfyba0"
            hdf5RuntimePackage="libhdf5-103-1"
            kmlBaseRuntimePackage="libkmlbase1"
            kmlDomRuntimePackage="libkmldom1"
            kmlEngineRuntimePackage="libkmlengine1"
            ;;
        bookworm)
            boostVersion="1.74.0"
            boostChronoVersion="1.74.0"
            sfcgalRuntimePackage="libsfcgal1"
            curlRuntimePackage="libcurl3-gnutls"
            cfitsioRuntimePackage="libcfitsio10"
            fybaRuntimePackage="libfyba0"
            hdf5RuntimePackage="libhdf5-103-1"
            kmlBaseRuntimePackage="libkmlbase1"
            kmlDomRuntimePackage="libkmldom1"
            kmlEngineRuntimePackage="libkmlengine1"
            ;;
        trixie)
            boostVersion="1.83.0"
            boostChronoVersion="1.83.0t64"
            sfcgalRuntimePackage="libsfcgal2"
            curlRuntimePackage="libcurl3t64-gnutls"
            cfitsioRuntimePackage="libcfitsio10t64"
            fybaRuntimePackage="libfyba0t64"
            hdf5RuntimePackage="libhdf5-310"
            kmlBaseRuntimePackage="libkmlbase1t64"
            kmlDomRuntimePackage="libkmldom1t64"
            kmlEngineRuntimePackage="libkmlengine1t64"
            ;;
        *)
            echo "ERROR: unsupported Debian suite ${suite}; stop" >&2
            return 1
            ;;
    esac
}

for version in "${versions[@]}"; do
    IFS=- read -r postgresVersion postgisVersion <<< "$version"
    postgresVersionMain="$(echo "$postgresVersion" | awk -F 'alpha|beta|rc' '{print $1}')"

    echo " "
    echo "---- generate Dockerfile for $version ----"
    echo "postgresVersion=$postgresVersion"
    echo "postgisVersion=$postgisVersion"
    alpineSuite="$defaultAlpineSuite"
    sourceBuiltDebian=false
    addressStandardizerBuildHash="$addressStandardizerGitHash"

    if ! select_debian_suite "$postgresVersionMain" "$postgisVersion"; then
        exit 1
    fi
    suite="$selectedSuite"
    set_debian_dependencies "$suite"
    h3PackageName="postgresql-${postgresVersionMain}-h3"
    h3VersionAmd64="$(printf '%s\n' "$versionListAmd64" | package_version "$h3PackageName" || true)"
    h3VersionArm64="$(printf '%s\n' "$versionListArm64" | package_version "$h3PackageName" || true)"
    if [ -n "$h3VersionAmd64" ] || [ -n "$h3VersionArm64" ]; then
        if [ "$h3VersionAmd64" != "$h3VersionArm64" ]; then
            echo "ERROR: ${h3PackageName} differs between amd64 (${h3VersionAmd64:-missing}) and arm64 (${h3VersionArm64:-missing})"
            exit 1
        fi
        h3PackageVersion="$h3VersionAmd64"
    else
        h3PackageVersion=""
        if [ "$postgisVersion" != "master" ]; then
            warning "official ${h3PackageName} package is unavailable for Debian ${suite}; generated smoke will keep H3 optional"
        fi
    fi
    pgroutingPackageName="postgresql-${postgresVersionMain}-pgrouting"
    pgroutingVersionAmd64="$(printf '%s\n' "$versionListAmd64" | package_version "$pgroutingPackageName" || true)"
    pgroutingVersionArm64="$(printf '%s\n' "$versionListArm64" | package_version "$pgroutingPackageName" || true)"
    if [ -n "$pgroutingVersionAmd64" ] || [ -n "$pgroutingVersionArm64" ]; then
        if [ "$pgroutingVersionAmd64" != "$pgroutingVersionArm64" ]; then
            echo "ERROR: ${pgroutingPackageName} differs between amd64 (${pgroutingVersionAmd64:-missing}) and arm64 (${pgroutingVersionArm64:-missing})"
            exit 1
        fi
        pgroutingPackageVersion="$pgroutingVersionAmd64"
    else
        pgroutingPackageVersion=""
        warning "official ${pgroutingPackageName} package is unavailable for Debian ${suite}; generated smoke will keep pgRouting optional"
    fi
    fullVersion="$(printf '%s\n' "$versionListAmd64" | package_version "postgresql-${postgresVersionMain}" || true)"
    armFullVersion="$(printf '%s\n' "$versionListArm64" | package_version "postgresql-${postgresVersionMain}" || true)"
    if [ "$fullVersion" != "$armFullVersion" ]; then
        echo "ERROR: PostgreSQL ${postgresVersionMain} package differs between amd64 (${fullVersion:-missing}) and arm64 (${armFullVersion:-missing})"
        exit 1
    fi

    optimized=""
    debianPostgisMajMin=""
    if [ "master" == "$postgisVersion" ]; then
        postgisPackageName=""
        postgisFullVersion="$postgisVersion"
        postgisMajor=""
        postgisDocSrc="development: postgis, geos, proj, gdal"
    else
        postgisMajMin="$( echo "${postgisVersion}" | cut -d. -f1 ).$( echo "${postgisVersion}" | cut -d. -f2 )"
        echo "postgisMajMin=${postgisMajMin}"
        if [ "$postgisMajMin" = '3.7' ]; then
            addressStandardizerBuildHash="$addressStandardizerReleaseGitHash"
        fi

        postgisPackageName="postgresql-${postgresVersionMain}-postgis-${postgisDebPkgNameVersionSuffixes[${postgisMajMin}]}"
        postgisFullVersion="$(printf '%s\n' "$versionListAmd64" | package_version "$postgisPackageName" || true)"
        armPostgisFullVersion="$(printf '%s\n' "$versionListArm64" | package_version "$postgisPackageName" || true)"
        if [ "$postgisFullVersion" != "$armPostgisFullVersion" ]; then
            echo "ERROR: ${postgisPackageName} differs between amd64 (${postgisFullVersion:-missing}) and arm64 (${armPostgisFullVersion:-missing})"
            exit 1
        fi
        echo "postgisPackageName=${postgisPackageName}"
        echo "postgisFullVersion=${postgisFullVersion}"

        debianPostgisMajMin="$( echo "${postgisFullVersion}" | cut -d. -f1 ).$( echo "${postgisFullVersion}" | cut -d. -f2 )"

        if [ "$debianPostgisMajMin" == "$postgisMajMin" ]; then
            echo "debian postgis version is OK "
            postgisMajor="${postgisDebPkgNameVersionSuffixes[${postgisMajMin}]}"
            postgisDocSrc="${postgisFullVersion%%+*}"
        else
            echo "debian postgis is not updated, different .. "
            postgisFullVersion=""
            postgisMajor=""
            postgisDocSrc=""
        fi
    fi

    if [ "$postgisVersion" != "master" ] && [ -z "$postgisFullVersion" ]; then
        echo "PGDG does not have PostGIS ${postgisMajMin}; generating a source-built Debian image"
        sourceBuiltDebian=true
        srcArchiveVersion="$(select_postgis_source_version "$postgisMajMin")"
        postgisFullVersion="$srcArchiveVersion"
        postgisDocSrc="$srcArchiveVersion"
        srcSha256="$(curl_download "https://github.com/postgis/postgis/archive/${srcArchiveVersion}.tar.gz" | sha256sum | awk '{ print $1 }')"
    fi

    optimized="debian"
    if [[ "$version" =~ (alpha|beta|rc|master) || "$postgisFullVersion" =~ (alpha|beta|rc) ]]; then
        optimized="test"
    fi
    echo "optimized=$optimized"

    if [ "$postgisVersion" = "master" ]; then
        (
            set -x
            cat Dockerfile.master.template > "$version/Dockerfile"
            sed_in_place 's/%%TXT_AUTOGENERATED%%/'"$autogenerated"'/g; s/%%PG_MAJOR%%/'"$postgresVersion"'/g; s/%%POSTGIS_MAJOR%%/'"$postgisMajor"'/g; s/%%POSTGIS_VERSION%%/'"$postgisFullVersion"'/g; s/%%H3_VERSION%%/'"$h3PackageVersion"'/g; s/%%PGROUTING_VERSION%%/'"$pgroutingPackageVersion"'/g; s/%%CGAL_GIT_BRANCH%%/'"$cgalGitBranch"'/g; s/%%POSTGIS_GIT_HASH%%/'"$postgisGitHash"'/g; s/%%H3_PG_GIT_HASH%%/'"$h3PgGitHash"'/g; s/%%ADDRESS_STANDARDIZER_GIT_HASH%%/'"$addressStandardizerGitHash"'/g; s/%%TIGER_GEOCODER_VERSION%%/'"$tigerGeocoderVersion"'/g; s/%%TIGER_GEOCODER_SHA256%%/'"$tigerGeocoderSha256"'/g; s/%%CGAL_GIT_HASH%%/'"$cgalGitHash"'/g; s/%%SFCGAL_GIT_HASH%%/'"$sfcgalGitHash"'/g; s/%%PROJ_GIT_HASH%%/'"$projGitHash"'/g; s/%%GDAL_GIT_HASH%%/'"$gdalGitHash"'/g; s/%%GEOS_GIT_HASH%%/'"$geosGitHash"'/g; s/%%BOOST_VERSION%%/'"$boostVersion"'/g; s/%%BOOST_CHRONO_VERSION%%/'"$boostChronoVersion"'/g; s/%%DEBIAN_VERSION%%/'"$suite"'/g; s/%%LIBCURL_RUNTIME_PACKAGE%%/'"$curlRuntimePackage"'/g; s/%%CFITSIO_RUNTIME_PACKAGE%%/'"$cfitsioRuntimePackage"'/g; s/%%FYBA_RUNTIME_PACKAGE%%/'"$fybaRuntimePackage"'/g; s/%%HDF5_RUNTIME_PACKAGE%%/'"$hdf5RuntimePackage"'/g; s/%%KML_BASE_RUNTIME_PACKAGE%%/'"$kmlBaseRuntimePackage"'/g; s/%%KML_DOM_RUNTIME_PACKAGE%%/'"$kmlDomRuntimePackage"'/g; s/%%KML_ENGINE_RUNTIME_PACKAGE%%/'"$kmlEngineRuntimePackage"'/g; s/%%NLOHMANN_JSON_VERSION%%/'"$nlohmannJsonVersion"'/g;' "$version/Dockerfile"
            echo "| [postgis/postgis:${version}](${dockerhublink}${version}) | [Dockerfile](${githubrepolink}/${version}/Dockerfile) | debian:${suite} | ${postgresVersion} | ${postgisDocSrc} |" >> "$dockerlistsDir/_dockerlists_${optimized}.md"
        )
    elif [ "$sourceBuiltDebian" = true ]; then
        postgisMinor="${postgisMajMin#*.}"
        (
            set -x
            cat Dockerfile.source.template > "$version/Dockerfile"
            sed_in_place 's/%%TXT_AUTOGENERATED%%/'"$autogenerated"'/g; s/%%PG_MAJOR%%/'"$postgresVersion"'/g; s/%%POSTGIS_VERSION%%/'"$postgisFullVersion"'/g; s/%%POSTGIS_SOURCE_VERSION%%/'"$srcArchiveVersion"'/g; s/%%POSTGIS_SHA256%%/'"$srcSha256"'/g; s/%%POSTGIS_MINOR%%/'"$postgisMinor"'/g; s/%%H3_VERSION%%/'"$h3PackageVersion"'/g; s/%%PGROUTING_VERSION%%/'"$pgroutingPackageVersion"'/g; s/%%ADDRESS_STANDARDIZER_GIT_HASH%%/'"$addressStandardizerBuildHash"'/g; s/%%TIGER_GEOCODER_VERSION%%/'"$tigerGeocoderVersion"'/g; s/%%TIGER_GEOCODER_SHA256%%/'"$tigerGeocoderSha256"'/g; s/%%DEBIAN_VERSION%%/'"$suite"'/g; s/%%SFCGAL_RUNTIME_PACKAGE%%/'"$sfcgalRuntimePackage"'/g;' "$version/Dockerfile"
            echo "| [postgis/postgis:${version}](${dockerhublink}${version}) | [Dockerfile](${githubrepolink}/${version}/Dockerfile) | debian:${suite} | ${postgresVersion} | ${postgisDocSrc} (source) |" >> "$dockerlistsDir/_dockerlists_${optimized}.md"
        )
    else
        (
            set -x
            cat Dockerfile.template > "$version/Dockerfile"
            sed_in_place 's/%%TXT_AUTOGENERATED%%/'"$autogenerated"'/g; s/%%PG_MAJOR%%/'"$postgresVersion"'/g; s/%%POSTGIS_MAJOR%%/'"$postgisMajor"'/g; s/%%POSTGIS_VERSION%%/'"$postgisFullVersion"'/g; s/%%H3_VERSION%%/'"$h3PackageVersion"'/g; s/%%PGROUTING_VERSION%%/'"$pgroutingPackageVersion"'/g; s/%%CGAL_GIT_BRANCH%%/'"$cgalGitBranch"'/g; s/%%POSTGIS_GIT_HASH%%/'"$postgisGitHash"'/g; s/%%H3_PG_GIT_HASH%%/'"$h3PgGitHash"'/g; s/%%ADDRESS_STANDARDIZER_GIT_HASH%%/'"$addressStandardizerGitHash"'/g; s/%%TIGER_GEOCODER_VERSION%%/'"$tigerGeocoderVersion"'/g; s/%%TIGER_GEOCODER_SHA256%%/'"$tigerGeocoderSha256"'/g; s/%%CGAL_GIT_HASH%%/'"$cgalGitHash"'/g; s/%%SFCGAL_GIT_HASH%%/'"$sfcgalGitHash"'/g; s/%%PROJ_GIT_HASH%%/'"$projGitHash"'/g; s/%%GDAL_GIT_HASH%%/'"$gdalGitHash"'/g; s/%%GEOS_GIT_HASH%%/'"$geosGitHash"'/g; s/%%BOOST_VERSION%%/'"$boostVersion"'/g; s/%%BOOST_CHRONO_VERSION%%/'"$boostChronoVersion"'/g; s/%%DEBIAN_VERSION%%/'"$suite"'/g; s/%%LIBCURL_RUNTIME_PACKAGE%%/'"$curlRuntimePackage"'/g; s/%%CFITSIO_RUNTIME_PACKAGE%%/'"$cfitsioRuntimePackage"'/g; s/%%FYBA_RUNTIME_PACKAGE%%/'"$fybaRuntimePackage"'/g; s/%%HDF5_RUNTIME_PACKAGE%%/'"$hdf5RuntimePackage"'/g; s/%%KML_BASE_RUNTIME_PACKAGE%%/'"$kmlBaseRuntimePackage"'/g; s/%%KML_DOM_RUNTIME_PACKAGE%%/'"$kmlDomRuntimePackage"'/g; s/%%KML_ENGINE_RUNTIME_PACKAGE%%/'"$kmlEngineRuntimePackage"'/g; s/%%NLOHMANN_JSON_VERSION%%/'"$nlohmannJsonVersion"'/g;' "$version/Dockerfile"

            echo "| [postgis/postgis:${version}](${dockerhublink}${version}) | [Dockerfile](${githubrepolink}/${version}/Dockerfile) | debian:${suite} | ${postgresVersion} | ${postgisDocSrc} |" >> "$dockerlistsDir/_dockerlists_${optimized}.md"
        )
    fi

    if [ "master" == "$postgisVersion" ] && [ -d "$version/alpine" ]; then
        alpineSuite="$(alpine_suite_for "$postgresVersion")"
        srcVersion="master"
        srcArchiveVersion="$postgisGitHash"
        srcSha256="$(curl_download "https://github.com/postgis/postgis/archive/$srcArchiveVersion.tar.gz" | sha256sum | awk '{ print $1 }')"
        postgisDocSrc=$srcVersion
    elif [ "master" == "$postgisVersion" ]; then
        srcVersion=""
        srcArchiveVersion=""
        srcSha256=""
    elif [ -d "$version/alpine" ]; then
        alpineSuite="$(alpine_suite_for "$postgresVersion")"
        srcVersion="$(select_postgis_source_version "$postgisMajMin")"

        srcArchiveVersion="$srcVersion"
        srcSha256="$(curl_download "https://github.com/postgis/postgis/archive/$srcVersion.tar.gz" | sha256sum | awk '{ print $1 }')"
        echo "Selected PostGIS version for Alpine: ${srcVersion}"
        postgisDocSrc=$srcVersion
    else
        srcVersion="${postgisFullVersion%%+*}"
        srcArchiveVersion="$srcVersion"
        srcSha256="$(curl_download "https://github.com/postgis/postgis/archive/$srcVersion.tar.gz" | sha256sum | awk '{ print $1 }')"
        postgisDocSrc=$srcVersion
    fi

    pgroutingVersion=""
    pgroutingSha256=""
    if [ -f "$version/alpine/pgrouting-version.txt" ]; then
        pgroutingVersion="$(tr -d '[:space:]' < "$version/alpine/pgrouting-version.txt")"
        if [[ ! "$pgroutingVersion" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: invalid pgRouting version for $version/alpine: $pgroutingVersion"
            exit 1
        fi
        if [ "$pgroutingVersion" != "$pgroutingLatestVersion" ]; then
            echo "Updating pgRouting version for $version/alpine: $pgroutingVersion -> $pgroutingLatestVersion"
            pgroutingVersion="$pgroutingLatestVersion"
            printf '%s\n' "$pgroutingVersion" > "$version/alpine/pgrouting-version.txt"
        fi
        pgroutingSha256="$(curl_download "https://github.com/pgRouting/pgrouting/releases/download/v${pgroutingVersion}/pgrouting-${pgroutingVersion}.tar.gz" | sha256sum | awk '{ print $1 }')"
    fi

    variant=alpine
    if [ -d "$version/$variant" ]; then
        (
            set -x
            if [ "$optimized" != "test" ]; then
              optimized="alpine"
            fi
            cp -p Dockerfile.alpine.template "$version/$variant/"
            mv "$version/$variant/Dockerfile.alpine.template" "$version/$variant/Dockerfile"
            addressStandardizerBuildHash="$addressStandardizerGitHash"
            if [ "$postgisVersion" != "master" ] && [ "$postgisMajMin" = '3.7' ]; then
                addressStandardizerBuildHash="$addressStandardizerReleaseGitHash"
            fi
            sed_in_place 's/%%TXT_AUTOGENERATED%%/'"$autogenerated"'/g; s/%%PG_MAJOR%%/'"$postgresVersion"'/g; s/%%POSTGIS_VERSION%%/'"$srcVersion"'/g; s/%%POSTGIS_SOURCE_VERSION%%/'"$srcArchiveVersion"'/g; s/%%POSTGIS_SHA256%%/'"$srcSha256"'/g; s/%%PGROUTING_VERSION%%/'"$pgroutingVersion"'/g; s/%%PGROUTING_SHA256%%/'"$pgroutingSha256"'/g; s/%%ADDRESS_STANDARDIZER_GIT_HASH%%/'"$addressStandardizerBuildHash"'/g; s/%%TIGER_GEOCODER_VERSION%%/'"$tigerGeocoderVersion"'/g; s/%%TIGER_GEOCODER_SHA256%%/'"$tigerGeocoderSha256"'/g; s/%%ALPINE_SUITE%%/'"$alpineSuite"'/g' "$version/$variant/Dockerfile"

            echo "| [postgis/postgis:${version}-${variant}](${dockerhublink}${version}-${variant}) | [Dockerfile](${githubrepolink}/${version}/${variant}/Dockerfile) | alpine:${alpineSuite} | ${postgresVersion} | ${postgisDocSrc} (source) |" >> "$dockerlistsDir/_dockerlists_${optimized}.md"
        )
    fi
done

echo "|-------------------------|"
echo "|-   Generated images    -|"
echo "|-------------------------|"

for optimized in debian alpine test; do
    echo " "
    echo "---- ${optimized} ----"
    cat "$dockerlistsDir/_dockerlists_${optimized}.md"
done

if [ "$fullMatrixUpdate" = true ]; then
    # update README.md only when all matrix fragments were regenerated.
    bash ./apply-readme.sh
else
    echo "README unchanged for selected versions."
fi

echo " "
echo "=============================="
echo " - update done && git status: "

git status
